# Generated by Django 4.0.1 on 2022-02-17 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_alter_fieldvaluessuggestion_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldvaluessuggestion',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('pk', None), models.Q(('app_label', 'personal_to_dos'), ('model', 'corevalue')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content type'),
        ),
    ]
