# Generated by Django 4.0.1 on 2022-02-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_fieldvaluessuggestion_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldvaluessuggestion',
            name='create_date',
            field=models.DateField(auto_now=True, verbose_name='Create date'),
        ),
    ]
